version: '3'
services:
  database:
    image: "postgres:latest"
    container_name: db_mercadolivro_local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_mercadolivro