spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/db_mercadolivro}
    username: postgres
    password: password

springdoc:
  packages-to-scan: com.devgabriel.mercadolivro.controller